// LOGIN
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

// LOGOUT
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

// SIGNUP
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

// VILLAGES
export const VILLAGES_REQUEST = 'VILLAGES_REQUEST';
export const VILLAGES_SUCCESS = 'VILLAGES_SUCCESS';
export const VILLAGES_ERROR = 'VILLAGES_ERROR';

// VILLAGE
export const VILLAGE_REQUEST = 'VILLAGE_REQUEST';
export const VILLAGE_SUCCESS = 'VILLAGE_SUCCESS';
export const VILLAGE_ERROR = 'VILLAGE_ERROR';

export const CREATE_VILLAGE_REQUEST = 'CREATE_VILLAGE_REQUEST';
export const CREATE_VILLAGE_SUCCESS = 'CREATE_VILLAGE_SUCCESS';
export const CREATE_VILLAGE_ERROR = 'CREATE_VILLAGE_ERROR';
